### ISSUE TITLE
Plugin fails with invalid header

### ISSUE THREAD

**Issue by monooso** [Previz-app/Py-Previz#10]
Migrated from https://github.com/Previz-app/previz-app/issues/2787

---
The C4D plugin currently fails all post requests.

The cause of this is a combo of the new headers not being fully cast to string, the request package the python library uses that validates header values to be strings (not integers) and the exact format of the C4D internal version numbers. 

Specifically the problem is with the `X-PREVIZ-PLATFORM-VERSION` header. In C4D this is reported as (in my latest version) `19053`.

This is set at the header value, but then `site-packages/requests/utils,py@check_header_validity` cancels the request because it sees that as an integer, not a string or bytes.

https://www.dropbox.com/s/2b41rt02g812wzz/Screenshot%202018-06-12%2016.39.33.png?dl=0

**Comment by monooso** [comment]
@joelbradbury I've updated the plugin to cast all header values to strings, but don't have an environment in which to test it.

If you have C4D set-up on your machine, could you give [this branch](https://github.com/Previz-app/Py-Previz/tree/issues/10-invalid-header) the once over? It'll be an awful lot quicker than me trying to get everything running.

**Comment by joelbradbury** [comment]
I do. I’ll package up, test (and assuming it fixes) release first thing tomorrow.

One point of interest which might indicate a larger issue somewhere - this only failed on POST requests in my testing. 

That either means we aren’t sending the full custom headers for all requests (when we should) or that something off happens on the validation of post requests on the client. 

Can you check we do set the headers for all requests? (Even if it’s just a visual check for now)
